name: Build and deploy to GitHub Pages

on:
  # With this the action can be launched manually from GitHub Actions tab:
  workflow_dispatch:
  # This makes the action run on each push to 'main' branch:
  push:
    branches: ["main"]

jobs:
  BuildEleventy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js current
        uses: actions/setup-node@v4
        with:
          node-version: current

      - name: Install dependencies & build
        run: |
          npm install
          npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          #publish_dir is the folder on the docker instance which eleventy builds the pages to.
          #it is not the docs folder in the repository
          publish_dir: ./_site
          #publish_branch is the branch in the repository.
          #this is where you need to point GitHub pages
          publish_branch: gh-pages
